version: '3'
services:


  ats7:
    image: labats7
    build:
      context: .
      dockerfile: docker/ats7/Dockerfile
    expose:
      - 8080
    ports:
      - "80:8080"
    depends_on:
      - nginx
    links:
      - nginx:linkednginx.net
      

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8002:80"
    volumes:
      - .:/app/
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

