FROM frolvlad/alpine-java
VOLUME /tmp


COPY boot-websocket/spring-boot-test-websocket-1.0-SNAPSHOT.jar app.jar
RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
