version: '3'
services:

    #Spring services with WebSocket endpoint
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile-backend
        expose:
            - 8081

    #NGINX proxy
    nginx:
        image: nginx:1.17.6
        ports:
            - "8002:80"
        volumes:
            - ./configs/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./configs/key.pem:/tmp/key.pem
            - ./configs/cert.pem:/tmp/cert.pem
        links:
            - backend
