version: '3'
services:

  #Armeria Proxy
  armeria:
    build:
      context: .
      dockerfile: ./Dockerfile-armeria
    ports:
      - "8443:8443"
    
    
    
  webmain:
    image: php:8.0.13-apache
    volumes:
      - ./webmain/:/var/www/html/
    ports:
      - "8001:80"

  webstatic:
    image: php:8.0.13-apache
    volumes:
      - ./webstatic/:/var/www/html/
    ports:
      - "8002:80"

  # webstatic:
    # build:
      # context: .
      # dockerfile: ./Dockerfile-static
    # environment:
      # - "GUNICORN_CMD_ARGS=--capture-output --error-logfile=error.log --access-logfile=access.log --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
    # ports:
      # - "8002:80"


  # webmain:
    # image: kennethreitz/httpbin
    # environment:
      # - "GUNICORN_CMD_ARGS=--capture-output --error-logfile=- --access-logfile=- --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
